site_name: Python Notes
pages:
  - Python Tutorial:
     - numbers: "numbers.md"
     - operators: "operators.md"
     - variables: "Variables.md"
     - variable scope : "variablescope.md"
docs_dir: chapters
theme: readthedocs
plugins:
    - search